Repository projectceladon/device-intel-sepolicy, pull requests merged in 2022-09, with the labels that each got.

#183 Sensor 2.0 android_T sepolicy
  sensors/mediation/file_contexts
  sensors/mediation/sensor_hal_default.te
  sensors/mediation/service_contexts
Labels: Valid commit message

#188 Add missing nodes for rw in sepolicy
  ethernet/common/genfs_contexts
Labels: Invalid commit message

#193 Add Trusty metadata sepolicy
  trusty/enabled/tee.te
Labels: PR approved

#186 Add vulkan pastel for mesa 22.0.3
  graphics/mesa/file_contexts
Labels: Valid commit message, PR approved
