Repository projectceladon/device-intel-sepolicy, pull requests merged in 2024-12, with the labels that each got.

#373 Fix the sepolicy build issue on public image
  graphics/screencast/cast_client_app.te
  graphics/screencast/cast_server.te
  graphics/screencast/file.te
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#374 Remove the genfs_context of /sys/class/udc
  aafd/genfs_contexts
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#371 adding missing sepolicy for intel evs app
  car/evs_intel_app.te
Labels: PR approved, Invalid commit message, Developer Approved, Engineering Build Successful

#377 Add graphics related sepolicy for hal_sensors_default
  sensors/mediation/sensor_hal_default.te
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#385 Grant logwrapper domain read permission for sysfs dirs/files
  vendor/logwrapper.te
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#382 Update the sepolicy of OTA Coordinator
  ota_coordinator/ota_coordinator.te
  ota_coordinator/property_contexts
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#386 Replace logwrapper domain with auto_detection
  aafd/auto_detection.te
  aafd/file_contexts
  aafd/logwrapper.te
  camera-ext/ext-camera-only/auto_detection.te
  camera-ext/ext-camera-only/logwrapper.te
  camera-ext/ivi/auto_detection.te
  camera-ext/ivi/logwrapper.te
  thermal/auto_detection.te
  thermal/logwrapper.te
  vendor/file_contexts
  vendor/logwrapper.te
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#383 Update sepolicy for audio hidl one image
  audio/audioserver.te
  audio/file_contexts
  audio/hal_audio_default.te
  audio/property.te
  audio/property_contexts
  audio/set_board_prop.te
  audio/vendor_init.te
Labels: Valid commit message, PR approved, Pending Developer Approval, Engineering Build Successful

#387 Correct audio property to vendor public
  audio/property.te
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful
