Repository projectceladon/device-intel-sepolicy, pull requests merged in 2024-08, with the labels that each got.

#328 Enable loading vendor.intel.video.codec based on sysfs
  aafd/logwrapper.te
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#329 Add sepolicy for application rendering setting property
  app_render_setting_property/platform_app.te
  app_render_setting_property/priv_app.te
  app_render_setting_property/property.te
  app_render_setting_property/property_contexts
  app_render_setting_property/system_app.te
  app_render_setting_property/system_server.te
  app_render_setting_property/untrusted_app_all.te
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#323 Add Widevine L3 sepolicy
  widevine/gen/gen_common/file.te
  widevine/gen/gen_common/file_contexts
  widevine/gen/gen_common/hal_drm_widevine.te
  widevine/gen/gen_common/service_contexts
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Not Started

#333 Enable AV1 encoder in DG2
  aafd/shell.te
  codec2/msdk-codec2/codec2_hal_default.te
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#332 Remove libpciaccess
  graphics/mesa/file_contexts
  graphics/mesa_acrn/file_contexts
  graphics/mesa_xen/file_contexts
  graphics/ufo_common/file_contexts
Labels: Valid commit message, PR approved, Pending Developer Approval, Engineering Build Successful

#335 Set proper file label for dri dir
  graphics/mesa/file_contexts
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#336 sepolicy for intel evs app
  car/evs_intel_app.te
  car/evsmanagerd.te
  car/file_contexts
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#331 Sepolicy for android_pm_tune script
  power/android_pm_tune.te
  power/file_contexts
  power/shell.te
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful
